- embedding/embedlite/embedthread/EmbedLiteCompositorBridgeParent.cpp
Wait for rendering to the offscreen surface to complete before compositing it into a QML scene.
> [sailfishos][embedlite] Fix flickering on animated web page in a web view. Fixes JB#54826 OMP#JOLLA-226

- rpm/0070-Do-not-flip-scissor-rects-when-rendering-to-an-offsc.patch
- rpm/xulrunner-qt5.spec
As PrepareViewport() does for the global transform, disable Y coordinate
flipping of scissor rectangles when targeting an offscreen window
surface.
> [xulrunner-qt5] Fix textarea content being clipped when the keyboard is visible. Fixes JB#54847 OMP#JOLLA-244

- rpm/0029-sailfishos-configure-Disable-LTO-for-rust-1.52.1-wit.patch
- rpm/xulrunner-qt5.spec
Fixing following error:
Compiling gkrust v0.1.0 (gecko-dev/toolkit/library/rust)
LLVM ERROR: out of memory
qemu: uncaught target signal 6 (Aborted) - core dumped
error: could not compile `gkrust`.
> [sailfishos][configure] Disable LTO for rust 1.52.1 with ESR78. JB#53019 OMP#JOLLA-93

- embedding/embedlite/EmbedLiteApp.cpp
- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/utils/GeckoLoader.cpp
This PR contains two main fixes. In addition, there are two small cleanup commits.
The first commit fixes initialization sequence. It should be following and there should
be reverse order in the TermEmbedding.
- NS_LogInit - sets main thread
- IOInterposer::Init
- profiler_init
GeckoProfiler.h states that profiler_init call must happen before any
other profiler calls.
The second commit removes wrong NS_LogTerm call as we do not have
"event loop" per se rather the constructed worker thread is our gecko main thread. Hence,
NS_LogTerm call should be only called from the TermEmbedding.
> Initialize profiler properly

- rpm/0031-sailfishos-fonts-Load-and-set-FTLibrary-for-the-Fact.patch
- rpm/xulrunner-qt5.spec
The same old FTLibrary loading issue but another incarnation of it.
The gfxFontGroup::GetDefaultFont of the gfxTextRun failed to
FindOrMakeFont gfxFont and set it as default font. The gfxFontEntry::FindOrMakeFont
itself failed to CreateFontInstance via gfxFontconfigFontEntry::GetFTFace
which fails because FTLibrary was not loaded by the platform. See more details from the
gfx/2d/Factory::NewSharedFTFace.
This commit adds FreeType library loading and setting up the
library for the Factory.
> [sailfishos][fonts] Load and set FTLibrary for the Factory. Fixes JB#55191 OMP#JOLLA-285

- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/utils/BrowserChildHelper.cpp
- embedding/embedlite/utils/BrowserChildHelper.h
Check the return value of nsDocShell::GetPresContext() before dereferencing it.
> [sailfishos][embedlite] Fix crash coming RecvSetIsActive calling RecvScheduleUpdate. Fixes JB#55281 OMP#JOLLA-312

- rpm/xulrunner-qt5.spec
This uses the date of the tarball (only used when tarball is created from tar_git, so only for OBS). As rebuilds only differ based on this timestamp in the .so files, this now makes them reproducible.
OBS will now report for example:
Retried build at Fri Sep  3 07:15:02 2021 returned same result, skipped
> [sailfishos][gecko] Force MOZ_BUILD_DATE env var in order to have more reproducible builds JB#55269 OMP#JOLLA-305

- rpm/0042-sailfishos-gecko-Avoid-incorrect-compiler-optimisati.patch
- rpm/xulrunner-qt5.spec
Whilst doing https://github.com/sailfishos/gecko-dev/pull/37 got one gcc crash and thought that is could have been caused by this but in reality was caused by my own change. As I already had this one backported decided to open this PR as well.
> [sailfishos][gecko] Bring back: 'Avoid incorrect compiler optimisation' patch. JB#55228 OMP#JOLLA-298

- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/embedthread/EmbedContentController.cpp
- embedding/embedlite/embedthread/EmbedContentController.h
PR contains two commits
1) Use APZEventState::ProcessSingleTap in EmbedLiteViewChild::RecvHandleSingleTap
2) Use MessageLoop to forward events
The current nsThread passed by the EmbedLiteViewParent does not
have event queue initialized i.e. it was initialized with nsThread()
constructor. This initialization step looks to be coming via
nsThreadManager::GetCurrentThread.
The MessageLoop has nsISerialEventTarget in place. Thus, it can be
used to forward events as we did in past.
This commit effectively reverts sha1 c5d20afd1dc6cee148d6f6b2a10f371558f72ef6
> Adapt EmbedLiteViewChild::RecvHandleSingleTap

- rpm/0045-Revert-Bug-1445570-Remove-EnsureEventualAfterPaint-t.patch
- rpm/xulrunner-qt5.spec
Revert a patch to remove an ensure eventual after paint event timer as
no event is delivered in embedlite without it.
The short explanation is that the root widget (an embedlite puppet
widget) of the PresContext where the event is scheduled, is not the same
root widget as in the ClientLayerManager (nsWindow) where the paint is
completed, so the nsView installed as the widget listener on the puppet
widget doesn't have the DidCompositeWindow called via
ClientLayerManager::DidComposite. And even with a redirect established
there's a subsequent failure because the DidComposite is a posted event
and the transaction it refers to is gone when it executes.
> [sailfishos][gecko] Fix delivery of MozAfterPaint events. JB#55286 OMP#JOLLA-310

- embedding/embedlite/PEmbedLiteView.ipdl
- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/embedshared/EmbedLiteViewChild.h
- embedding/embedlite/embedshared/EmbedLiteViewChildIface.h
- embedding/embedlite/embedshared/EmbedLiteViewParent.cpp
- embedding/embedlite/embedshared/EmbedLiteViewParent.h
- embedding/embedlite/utils/BrowserChildHelper.cpp
- embedding/embedlite/utils/BrowserChildHelper.h
- rpm/0003-sailfishos-ipc-Whitelist-sync-messages-of-EmbedLite..patch
This PR fixes MessageManagerCallback overrides of the BrowserChildHelper making sendAsyncMessage and sendSyncMessage (MessageManagerGlobal.h) to work. We missed this override as MessageManagerCallback (nsFrameMessageManager.h) is not pure virtual rather having dummy implementations. 
Second commit removes obsolete RpcMessage.
> Fix MessageManagerCallback overrides

- embedding/embedlite/utils/DirProvider.cpp
Tried to find a way to do this without a patch but didn't figure out any other way. Also the paths could be more dynamic but couldn't find any way to retrieve them.
> [sailfishos][embedlite] Fix search plugin directories. JB#55267 OMP#JOLLA-304

- embedding/embedlite/tests/content/embedScrollStyles.css
This will make it possible to utilize fully space on the right hand side.
For testing one can update omni.ja by following steps listed here:
https://sailfishos.org/wiki/WorkingWithBrowser#Debugging_omni.ja_of_gecko
> [sailfishos][embedlite] Adjust embed scroll style. Fixex JB#55306 OMP#JOLLA-322

- embedding/embedlite/installer/package-manifest.in
There are two new folders included to the omni.ja:
- hyphenation
- localization
Seems that Gecko is shifting towards Fluent (*.fl).
> [sailfishos][embedlite] Adapt package-manifest.in from Android FF. Fixes JB#55467 OMP#JOLLA-358

- embedding/embedlite/tests/content/embedScrollStyles.css
[sailfishos][embedlite] Add dummy preprocessor directive. Fixex JB#55306 OMP#JOLLA-322
mozbuild.preprocessor.Error: ('mobile/sailfishos/tests/content/embedScrollStyles.css',
None, 'no preprocessor directives found', None)
sha1 a7ff1cbcd0394dc3febd646fcfdb41733580f0c7 was a bit too much.
> Add dummy preprocessor directive

- rpm/0072-sailfishos-gecko-Fix-audio-underruns-for-fullduplex-.patch
- rpm/xulrunner-qt5.spec
Move audio rendering from the pulseaudio callback to a separate thread.
> [sailfishos][gecko] Fix audio underruns for fullduplex mode. JB#55461

- rpm/xulrunner-qt5.spec
Running with a startupCache can cause unexpected behaviour when old code
in the cache is used instead of updated code.
This is intended as a temporary change during development.
> Disable startupCache for all architectures. Fixes JB#55487 OMP-JOLLA-373

- rpm/xulrunner-qt5.spec
Previously the final link step was failing on arm builds due to
out-of-memory issues (it seemed to run out of address space on the
32-bit SDK).
Something seems to have changed, since it now passes through okay, so
this change makes it so that it no longer strip the debug symbols.
> Avoid stripping debug symbols during final link step on arm. JB#55074 OMP#JOLLA-269

- embedding/embedlite/utils/BrowserChildHelper.cpp
- embedding/embedlite/utils/BrowserChildHelper.h
This commit brings back APZCCallbackHelper::ApplyCallbackTransform
that got dropped in commit sha1
https://github.com/sailfishos/gecko-dev/commit/1ae1775925319d69c96e4ca7b4740cd85447a7e9
This follows up changes done to APZCCallbackHelper and ViewportUtils
in context of https://bugzilla.mozilla.org/show_bug.cgi?id=1556556 .
Following changes will depict what's needed:
Bug 1556556 - Move GetCallbackTransform() into a new ViewportUtils class. r=kats
- https://github.com/sailfishos-mirror/gecko-dev/commit/f02fcb17b46f9fdb229f2d17b91c88276a105384
Bug 1556556 - Have GetCallbackTransform take just a scroll id rather than an entire guid. r=kats
- https://github.com/sailfishos-mirror/gecko-dev/commit/6a461317ca50e7bb072ce6b354d2629118ce6a43
Bug 1556556 - Remove …
> [sailfishos][embedlite] Call ViewportUtils::GetVisualToLayoutTransform to touch point position. Fixes JB#55472 OMP#JOLLA-365

- rpm/0023-sailfishos-gecko-Force-to-build-mozglue-and-xpcomglu.patch
- rpm/0046-sailfishos-gecko-Prioritize-GMP-plugins-over-all-oth.patch
- rpm/0047-sailfishos-gecko-Force-recycling-of-gmp-droid-instan.patch
- rpm/xulrunner-qt5.spec
Rebase patches and fix a crash in plugin-container resulting from
mozglue being a static library and unreferenced symbols being excluded.
> [sailfishos][gecko] Adapt GMP patches from ESR60. JB#55479 OMP#JOLLA-366

- rpm/0048-sailfishos-egl-Drop-swap_buffers_with_damage-extensi.patch
- rpm/xulrunner-qt5.spec
At least on "Adreno (TM) 508" swapping with damage triggered a hang on the
compositor thread i.e. call never returns. Conceptually I think we should
bind eglSwapBuffersWithDamage on hybris side to the eglSwapBuffers or something like that.
Co-authored-by: David Llewellyn-Jones <david.llewellyn-jones@jolla.com>
Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>
> [sailfishos][egl] Drop swap_buffers_with_damage extension support. Fixes JB#55571 OMP#JOLLA-396

- .gitmodules
Updates the gecko-dev submodule to the new mirror at
https://github.com/sailfishos-mirror/gecko-dev.git
After pulling down this change, the following must be run in your local
repostory to propagate the change.
git submodule sync --recursive
> Update submodule to new gecko-dev mirror. Fixes JB#55712 OMP#JOLLA-406

- embedding/embedlite/embedding.js
There is no default value in the all.js. Hence, following error
could occur:
1633050956927	addons.manager	WARN	Error in background update: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/AddonManager.jsm :: systemUpdateEnabled :: line 1287"  data: no] Stack trace: systemUpdateEnabled()@resource://gre/modules/AddonManager.jsm:1287
backgroundUpdateCheck/buPromise<()@resource://gre/modules/AddonManager.jsm:1366
backgroundUpdateCheck()@resource://gre/modules/AddonManager.jsm:1378
backgroundUpdateTimerHandler()@resource://gre/modules/AddonManager.jsm:3502
notify()@resource://gre/modules/addonManager.js:174 …
> [sailfishos][embedlite] Define extensions.systemAddon.update.enabled as false. Fixes JB#55751 OMP#JOLLA-416

- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
When vkb closes its height is set to zero but toolbar height was not changed, this fixes that.
> [sailfishos][embedlite] Reset toolbar height after vkb closes. Fixes JB#55497 OMP#JOLLA-382

- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/embedshared/EmbedLiteViewChild.h
- embedding/embedlite/utils/WebBrowserChrome.cpp
- rpm/0049-Revert-Bug-1494175-Remove-unimplemented-nsIWebBrowse.patch
- rpm/xulrunner-qt5.spec
This PR contains 3 commits
1) Pass parent browsing context to a child view that is created with window.open
2) Partially Revert "Bug 1494175 - Remove unimplementet nsIWebBrowserChrome methods" to make window.close to work again: https://github.com/sailfishos-mirror/gecko-dev/commit/578ac09f67274b520071a3ef0052405cde0ef9f0
3) Introduce back DestroyBrowserWindow method implementation
On context of debugging 1st commit and why window.close was not working it became clear that nsGlobalWindowOuter::ReallyCloseWindow and treeOwnerAsWin->Destroy() didn't do anything.
> Adapt window.open and window.close to work

- embedding/embedlite/utils/BrowserChildHelper.cpp
- rpm/0050-sailfishos-gecko-Force-use-of-mobile-video-controls..patch
- rpm/xulrunner-qt5.spec
The embedlite message manager needs to be registered with JSActorService. And then the mobile variant of the controls should be favored for Sailfish.
> [sailfishos][embedlite] Fix child actor services not receiving events. JB#55484 OMP#JOLLA-371

- embedding/embedlite/components/nsClipboard.h
- embedding/embedlite/modules/EmbedLiteAppService.h
This helps when logging with MOZ_LOG="nsComponentManager:5" and
checking loaded / created components.
> [sailfishos][embedlite] Add string formatted component CID in comments

- rpm/0016-sailfishos-qt-Provide-checkbox-radio-renderer-for-Sa.patch
Minor errors in the patch prevented it from being applied in this way.
This reformatting fixes it so that
git am rpm/*.patch
will now work correctly.
> Reformat patch to allow git am to work

- rpm/0076-sailfishos-gecko-Ignore-safemode-in-gfxPlatform.-Fix.patch
Browser crashes without this like it did with esr60. This PR adapt the old patch.
> [sailfishos][gecko] Adapt safemode patch. Fixes JB#55764 OMP#JOLLA-422

- embedding/embedlite/embedthread/EmbedLiteCompositorBridgeParent.cpp
Previously, the variable existed because a template function could
not accept `nullptr` as a parameter; this was fixed upstream, and
the code was updated to pass `nullptr` directly, but the variable
was never removed, resulting in compiler warning.
> [sailfishos][embedlite] Remove unused variable. Contributes to JB#55799

- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/utils/EmbedLiteSecurity.cpp
- rpm/0077-sailfishos-docshell-Align-fix-parentprocess-checks.-.patch
- rpm/xulrunner-qt5.spec
Contains 3 commits:
1. First one makes it possible to use nsSecureBrowserUI and update it
when location is changed. Follow up commit will create nsSecureBrowserUI.
2. Fix crash in EmbedLiteSecurity
3. Create Secure Browser UI when gecko window created
> Fix Security info (secure/unsecure) to appear to the toolbar

- rpm/0083-sailfishos-gecko-Allow-LoginManagerPrompter-to-find-.patch
- rpm/xulrunner-qt5.spec
This patch blocks loading of gecko's LoginManagerAuthPrompter.jsm so that the embedlite-components version can be used instead.
It also patches the `nsILoginManagerPrompter` interface to allow a reference to the window to be passed through, to allow the embedlite component to understand its context.
> [sailfishos][gecko] Allow LoginManagerPrompter to find its window. JB#55760 OMP#JOLLA-418

- rpm/xulrunner-qt5.spec
- No changes were needed for any patch which is kinda surprising
- Created test builds for i486 and arm
- Built qtmozembed, sailfish-components-webview, and sailfish-browser on top of this, quick smoke => it starts
Depending on in which order new changes land we may need to adjust this. Tried to cherry-pick changes from https://github.com/sailfishos/gecko-dev/pull/99 and at least that change applies nicely on top this as well.
> [sailfishos][gecko] Bump up to latest 78.15.1 sha1. Fixes JB#55681 OMP#JOLLA-402

- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
When the active tab is closed another tab will be made active and start
to load, if that tab is closed while loading the parent puppet widget can be
destroyed before the content view is created causing a failure in the
content view construction the error from which gets interpreted as the
unsupported document type and the browser falls back to downloading.
There is a failure case for when this happens and the DocShell is in
destroyed state which cancels the loading the document, so we can do the
same if the puppet widget has been destroyed.
> [sailfishos][gecko] Fix download starting when multiple tabs are closed. JB#56047 OMP#JOLLA-476

- rpm/0072-sailfishos-gecko-Fix-audio-underruns-for-fullduplex-.patch
During call setup, the audio buffer latency may become high because
the engine does a lot of work. Due to a bug in libcubeb. it may start
dropping audio data instead of writing it to the pulseaudio sink input.
> [sailfishos][gecko] Fix no audio during WebRTC call. JB#56302

- embedding/embedlite/embedding.js
Once enabled from window.visualViewport we can for instance get visual
viewport offset from the top-left corner.
> [sailfishos][embedlite] Enable VisualViewport API. JB#56066 OMP#JOLLA-479

- embedding/embedlite/embedding.js
- rpm/0084-sailfishos-gecko-dev-Disallow-page-zooming-if-the-me.patch
- rpm/xulrunner-qt5.spec
It was disabled because the APZ page zoom gets priority access to pinch
gestures which meant custom zooming using the pointer events didn't work
on some sites, but a fallback to legacy touch APIs did work if the
pointer API wasn't available did. Other sites have the inverse problem
where their fallback code paths have rotted and they don't work without
the pointer API.
The page zoom getting priority issue can be mitigated by disabling it if
the page sets both the meta viewport minimum and maximum scales to 1.
> [sailfishos][gecko-dev] Enable the pointer event API. JB#56149 OMP#JOLLA-499

- embedding/embedlite/EmbedLiteApp.cpp
- embedding/embedlite/embedshared/EmbedLiteAppChild.cpp
Cherry-picking https://github.com/sailfishos/gecko-dev/pull/110 to the master.
> [sailfishos][embedlite] Prevent invalid manifest location from being added. Fixes JB#56395

- rpm/0071-sailfishos-webrtc-Implement-video-capture-module.-JB.patch
This commit handles the situation when the engine calls StartCapture()
with different resolution settings for the camera, without stopping it first.
> [sailfishos][gecko] Restart the camera when changing the resolution. JB#56415

- rpm/0084-sailfishos-gecko-Fix-audio-underruns-for-fullduplex-.patch
- rpm/xulrunner-qt5.spec
Move audio rendering from the pulseaudio callback to a separate thread.
> [sailfishos][gecko] Fix audio underruns for the fullduplex mode. JB#56317

- rpm/0072-sailfishos-gecko-Fix-audio-underruns-for-fullduplex-.patch
Fix typo which leads to a crash if the input and output formats are
different. Also do not perform volume scaling if the scale factor is 1.
> [sailfishos][gecko] Fix sound for the full duplex mode. JB#56443

- embedding/embedlite/embedding.js
See https://github.com/sailfishos-mirror/gecko-dev/blob/esr78/modules/libpref/init/all.js#L1352
> [sailfishos][embedlite] Http max-connections to 40. Fixes JB#56477 OMP#JOLLA-555

- embedding/embedlite/EmbedLiteView.h
- embedding/embedlite/PEmbedLiteView.ipdl
- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/embedshared/EmbedLiteViewChild.h
- embedding/embedlite/embedthread/EmbedContentController.cpp
In order to dig out the root scrollable rect from the LayerManager,
let's drop unused root frame argument as it is unused.
> [sailfishos][embedlite] Drop root frame argument from the PEmbedLiteView.ipdl and EmbedLiteViewListener::HandleScrollEvent. JB#56312 OMP#JOLLA-530

- rpm/xulrunner-qt5.spec
This commit effectively reverts sha1 bd5f5923ce6662c8bf8b3c4337
> [sailfishos][rpm] Re-enable startup cache for all arch except x86. Fixes JB#55488 OMP#JOLLA-374

- embedding/embedlite/modules/EmbedFrame.cpp
- embedding/embedlite/modules/EmbedFrame.h
- embedding/embedlite/modules/EmbedFrame.webidl
- embedding/embedlite/moz.build
- embedding/embedlite/utils/BrowserChildHelper.cpp
A message handler in RemotePageHandler was failing because it attempted
to install an event handler on the target of the received message but
addEventListener wasn't a didn't exist on EmbedFrame. The equivalent
object in Firefox appears to MozBrowser which is a javascript defined
object so there isn't a direct translation, but similarly structured
interfaces appear to be defined in webidl and extend EventTarget.
> [sailfishos][embedlite] Make EmbedFrame an EventListener. JB#56094 OMP#JOLLA-492

- rpm/0038-sailfishos-embedlite-egl-Fix-mesa-egl-display-and-bu.patch
A static function in the code had return value `bool`, but no return statement. The compiler then optimised this undefined behaviour into a crash (calling an otherwise guarded `dlopen` with an invalid parameter).
This change removes the crash by setting the return as void. Now the `dlopen` is only called when it's supposed to be.
Thanks to @Tomin1 and especially @spiiroin for noticing the incorrect code.
This change also fixes up an incorrectly named variable.
> Fix egl patch to prevent crashing. Fixes JB#56606 OMP#JOLLA-565

- embedding/embedlite/EmbedLiteApp.cpp
- embedding/embedlite/EmbedLiteApp.h
- embedding/embedlite/PEmbedLiteApp.ipdl
- embedding/embedlite/embedprocess/EmbedLiteAppProcessChild.cpp
- embedding/embedlite/embedprocess/EmbedLiteAppProcessChild.h
- embedding/embedlite/embedprocess/EmbedLiteAppProcessParent.cpp
- embedding/embedlite/embedprocess/EmbedLiteAppProcessParent.h
- embedding/embedlite/embedprocess/EmbedLiteViewProcessChild.cpp
- embedding/embedlite/embedprocess/EmbedLiteViewProcessChild.h
- embedding/embedlite/embedprocess/EmbedLiteViewProcessParent.cpp
- embedding/embedlite/embedprocess/EmbedLiteViewProcessParent.h
- embedding/embedlite/embedshared/EmbedLiteAppChild.cpp
- embedding/embedlite/embedshared/EmbedLiteAppChild.h
- embedding/embedlite/embedshared/EmbedLiteAppChildIface.h
- embedding/embedlite/embedshared/EmbedLiteAppParent.h
- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/embedshared/EmbedLiteViewChild.h
- embedding/embedlite/embedshared/EmbedLiteViewParent.cpp
- embedding/embedlite/embedshared/EmbedLiteViewParent.h
- embedding/embedlite/embedthread/EmbedLiteAppThreadChild.cpp
- embedding/embedlite/embedthread/EmbedLiteAppThreadChild.h
- embedding/embedlite/embedthread/EmbedLiteAppThreadParent.cpp
- embedding/embedlite/embedthread/EmbedLiteAppThreadParent.h
- embedding/embedlite/embedthread/EmbedLiteViewThreadChild.cpp
- embedding/embedlite/embedthread/EmbedLiteViewThreadChild.h
- embedding/embedlite/embedthread/EmbedLiteViewThreadParent.cpp
- embedding/embedlite/embedthread/EmbedLiteViewThreadParent.h
- embedding/embedlite/utils/WindowCreator.cpp
This commit makes it possible to pass back parent browsing context when
new view is created.
See also:
https://github.com/sailfishos/sailfish-browser/pull/961
https://github.com/sailfishos/qtmozembed/pull/30
> Pass parent browsing context down to CreateNewWindowRequested

- embedding/embedlite/components/nsClipboard.h
The CID used to access the clipboard service in nsCopySupport fails (it doesn't match the CID of nsIClipboard). This prevents the embedlite nsIClipboard service from being accessed.
Using the contract ID instead of the CID allows it to be accessed correctly.
> Ensure clipboard service can be accessed. Fixes JB#56647 OMP#JOLLA-578

- embedding/embedlite/utils/WebBrowserChrome.cpp
- embedding/embedlite/utils/WebBrowserChrome.h
If browser.tabs.documentchannel is enabled first request coming to WebBrowserChrome is prefixed with "documentchannel:" which causes it to fail to notify user-agent changes.
> [sailfishos][embedlite] Fix user agent notify. Fixes JB#56714 OMP#JOLLA-605

- rpm/0083-sailfishos-gecko-dev-Disallow-page-zooming-if-the-me.patch
If desktop mode is active then we should allow page zoomingi by the user (pinch-to-zoom), even if the metadata for the page has "user-scalable=no" set.
> Ensure zooming is always allowed if desktop mode is active. Fixes JB#56767 OMP#JOLLA-609

- embedding/embedlite/embedding.js
The nsDocShell can trigger directly external protocol service regardless
of the anchor target without creating new tab. Exposed protocols are only
checked by the nsDocShell. Hence, this ought to be safe.
> [sailfishos][embedlite] Load external uris directory via nsIExternalProtocolService. Fixes JB#56648 OMP#JOLLA-577

- embedding/embedlite/embedding.js
- embedding/embedlite/embedshared/EmbedLiteViewChild.cpp
- embedding/embedlite/embedthread/EmbedContentController.cpp
Ensure that double taps are passed on to the embedhelper.js, so they can be passed on to any javascript handlers.
Set the decision about whether to zoom on double tap follow the decision made by nsLayoutUtils::AllowZoomingForDocument().
> Pass double taps to embedhelper.js. JB#56765 OMP#JOLLA-607

- rpm/0087-sailfishos-gecko-Fix-memory-reporting-of-wasm-memory.patch
- rpm/xulrunner-qt5.spec
Backported from upstream gecko 94, bug 1615988.
This commit makes several tweaks to memory reporting for wasm memory.
* Add a field for shared wasm memory and track it in SAB.
- Before this commit, shared wasm memory wouldn't report its guard
pages but should.
* Track wasm guard pages in RuntimeSizes, not ClassInfo
- We want wasm guard pages to show as a top-level memory report
item, similar to vmem, and not under the owning array object.
Displaying under the owning object bloats the tree of memory usage
with large amounts of memory that's only reserved and not
committed, which is confusing. Before this commit the class info
reporter would try to make this happen, but this approach was
broken and the simplest fix is to
track this on RuntimeSizes and report the value from their.
* Only add …
> [sailfishos][gecko] Fix memory reporting of wasm memory. Fixes JB#56908

- embedding/embedlite/embedding.js
- rpm/0081-sailfishos-webrtc-Implement-video-capture-module.-JB.patch
- rpm/0089-sailfishos-gecko-Add-a-video-decoder-based-on-gecko-.patch
This enables platform decoder for VPx encoded video during WebRTC calls and supports GraphicBuffer API of the gecko-camera.
Depends on https://github.com/sailfishos/gecko-camera/pull/7.
> [sailfishos][gecko] Add support for gecko-camera GraphicBuffer, JB#56755

- rpm/0090-sailfishos-gecko-Disable-debug-info-for-rust.patch
- rpm/xulrunner-qt5.spec
This patch disables the generation of debug information for rust and
returns the contents of the debuginfo package.
Add 'a' character to the milestone in rpm/xulrunner-qt5.spec to build
an alpha version of the engine.
> [sailfishos][gecko] Do not remove debugging symbols

- embedding/embedlite/utils/DirProvider.cpp
Only if profile directory is not available, use hardcoded path.
Currently all browser downloaded search engines are leaking to
all other apps using engine.
This is last change to get tst_searchengine of QtMozEmbed properly with local runs. When running locally test case saw also browser installed search engines and only way to avoid that was to remove browser installed search engines.
> [sailfishos][embedlite] Prefer profile directory for search engines. Fixes JB#57275

- rpm/0091-sailfishos-gecko-Initialise-SVGGeometryProperty-Reso.patch
- rpm/xulrunner-qt5.spec
During SVG rendering HasValidDimensions() was sporadically returning false, causing some SVG elements not to render correctly.
The problem appears to be an optimisation glitch. This change initialises the parameters passed by reference to SVGGeometryProperty::ResolveAll, so that the compiler doesn't determine that they may be undefined.
> [sailfishos][gecko] Initialise SVGGeometryProperty::ResolveAll parameters. JB#56892

- embedding/embedlite/EmbedLiteView.cpp
- embedding/embedlite/embedshared/EmbedLiteViewIface.idl
- embedding/embedlite/embedshared/EmbedLiteViewParent.cpp
- embedding/embedlite/embedshared/nsWindow.cpp
- embedding/embedlite/embedshared/nsWindow.h
- embedding/embedlite/embedthread/EmbedContentController.cpp
- embedding/embedlite/embedthread/EmbedContentController.h
When multiple WebView componennts are used in an app, since there is
only one compositor, only one can be in direct use at a time. This will
be the last that was set as active.
When the currently activated component is deactivated, the WebView that
was active prior to that should be reinstanted. In particular, the
view's GeckoContentController needs to be reinstated.
This change adds a stack for managing the content controllers, so that
previously active controllers can be reactivated.
> [sailfishos][embedlite] Add a content controller stack. Fixes JB#57690

- embedding/embedlite/tests/content/embedScrollStyles.css
Remove the restriction on the maximum size of radio and checkbox input elements, so that they can be made larger than the default.
This is to match the behaviour of desktop and Android Firefox.
In particular, this fixes a but that prevented [Material toggle button components](https://material-components.github.io/material-web/demos/switch) from working correctly.
> [sailfishos][embedlite] Drop radio and checkbox max size restriction. Fixes JB#57693

- rpm/0092-sailfishos-build-Add-support-for-aarch64-to-elfhack..patch
- rpm/xulrunner-qt5.spec
Applies the upstream patches to allow elf-hack support on aarch64 (thanks @krnlyng for identifying them), and enables elf-hack to run for all Sailfish architectures.
> [sailfishos][build] Enable elf-hack. Fixes JB#57563

- embedding/embedlite/tests/content/embedScrollStyles.css
This covers textarea, input, select, and button.
Instructions regarding [omni debugging](https://docs.sailfishos.org/Reference/Core_Areas_and_APIs/Browser/Working_with_Browser/#debugging-omnija-of-gecko) helps when testing this.
> [sailfishos][embedlite] Clean background gradients from input elements. Fixes JB#58457

- rpm/0093-sailfishos-gecko-Add-support-for-prefers-color-schem.patch
- rpm/xulrunner-qt5.spec
Adds support to qt/nsLookAndFeel for the prefers-color-scheme media tag. The renderer already supports it by setting the ui.systemUsesDarkTheme preference to 0 or 1.
This patch allows, in addition, for the colour scheme to be controlled by sending an "ambience-theme-changed" notification with a data payload of either "light" or "dark". If the ui.systemUsesDarkTheme preference is unset or set to 2, the notification value will be used to control the theme instead.
This functionality is used to update the colour scheme based on the ambience of the device.
> [sailfishos][gecko] Add support for prefers-color-scheme. JB#58394

- embedding/embedlite/tests/content/embedScrollStyles.css
This reverts back default white background color for elements that used to have white background color https://github.com/sailfishos/gecko-dev/pull/148/files
Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>
> [sailfishos][embedlite] Revert back white default background colors. Fixes JB#59906

- rpm/0094-Bug-1750760-Create-ffmpeg59-module-for-ffmpeg5.0-r-a.patch
- rpm/0095-Bug-1750760-Open-libavcodec.so.59-library-and-bind-f.patch
- rpm/0096-Bug-1750760-Update-audio-and-video-decoders-to-ffmpe.patch
- rpm/0097-Bug-1761471-FFmpeg-5.0-Get-frame-color-range-and-col.patch
- rpm/0098-Bug-1758948-FFmpeg-Use-AVFrame-pts-instead-of-AVFram.patch
- rpm/xulrunner-qt5.spec
After update to ffmpeg 5.0 the support for various codecs was lost and backport of the support for ffmpeg 5.0 is needed for those to work again.
> [sailfishos][gecko] Backport support for ffmpeg 5.0. JB#60117 JB#60086

- rpm/0043-sailfishos-gecko-Supress-URLQueryStrippingListServic.patch
See also: https://github.com/sailfishos/sailfish-browser/issues/1065
> [sailfishos][gecko] Suppress URLQueryStrippingListService.jsm error improvement

- embedding/embedlite/embedding.js
It seems that "0.1f" value is no longer getting through as a float like it used to. The all.js of gecko-dev confirms this as there are no longer f-suffixed floats.
This commit cleans f-suffixed float prefs from embedding.js.
GitHub issue:
https://github.com/sailfishos/sailfish-browser/issues/1038
> [sailfishos][embedlite] Cleanup float preferences. JB#62618

- embedding/embedlite/tests/content/embedScrollStyles.css
This PR contains two commits. Both commits touches html and body default css values:
- First one fixes default font to sans-serif
- Second one margin & padding to zero
Changes are synchronized from Android FF 91 https://github.com/sailfishos-mirror/gecko-dev/blob/78d17b06b04f2b76bcb6e3e2a553f4ad0202bc8d/mobile/android/themes/geckoview/config.css
To be noted that these were broken on ESR 78 as well.
GitHub issue:
https://github.com/sailfishos/sailfish-browser/issues/1083
https://github.com/sailfishos/sailfish-browser/issues/1084
> EmbedLite css default value fixes

- rpm/xulrunner-qt5.spec
This commit partially reverts e173c16fc603426983625449267606e3e86cff0a so that only Rust `cargo` builds single-threaded, but lets other compiler processes compile with multiple threads. This should reduce compilation time, still preventing hanging both locally and in OBS.
> Make only Rust compile single threaded
